title: Node Scan Results
email: cbyrne@arizona.edu
description: Results from a security scan of custom nodes
baseurl: "node-scan-results" # the subpath of your site, e.g. /blog
url: "https://christian-byrne.github.io/node-sec-scan/node-scan-results/" # the base hostname & protocol for your site

twitter_username: c__byrne
github_username: christian-byrne

# Build settings
markdown: kramdown
